config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'users#show'
  get 'projects/show'
  get 'projects/new'
  get 'projects/edit'
  get 'task/show'

  resources :projects do
    member do
      post :join
      delete :leave
    end
    resources :members
  end
  resources :associates
  resources :posts
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :host_users_associate, -> {where(host: :true)},class_name: 'Associate'
  has_many :host_users, through: :host_users_associate, source: :user
  has_many :associates, dependent: :destroy
  has_many :users, through: :associates
  has_many :posts, dependent: :destroy

  validates :name, :topic1, presence: true
  validates :name, {length: {maximum: 15}}
  mount_uploader :icon, ImageUploader
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(projects_params)
    #確認
    if @project.save
      redirect_to @project
    else
      error_mes = ""
      @project.errors.full_messages.each do |error|
        error_mes += "!#{error}<br>"
      end
      flash[:alert] = error_mes.html_safe
      render :show
    end
  end


  private
    def projects_params
      params.require(:project).parmit(:name, :icon, :note)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
    @host_member = @project.users.where(associates: {host: true})
    @not_host_member = @project.users.where(associates: {host: false})
    @posts = @project.posts.page(params[:page]).per(6)
  end

  def edit
    @project = Project.find(params[:id])
    @host_member = @project.users.where(associates: {host: true}).where.not(associates: {user: current_user.id})
    @not_host_member = @project.users.where(associates: {host: false})
  end

  def create
    @project =  current_user.projects.new(projects_params)
    #確認
    if current_user.save
      set_host
      redirect_to @project
    else
      error_mes = ""
      @project.errors.full_messages.each do |error|
        error_mes += "!#{error}<br>"
      end
      flash[:alert] = error_mes.html_safe
      redirect_to 'new'
    end
  end

  def update
    @project = Project.find(params[:id])
    host = params[:project][:host_users]
    if host.present?
      new_host(host)
    end
    non_host = params[:project][:non_host]
    if non_host.present?
      delete_host(non_host)
    end
    if @project.update(projects_params)
      # update メソッドが正しく実行できたとき詳細ページに戻る
      redirect_to @project
      flash[:notice] = "正常にアップデートされました"
    else
      # updateできなかったときにエラーを表示
      flash[:alert] = "エラー：#{@project.errors.full_messages}"
      # renderで入力した内容はそのままで変種ページに戻る
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:notice] = "正常に削除されました"
      redirect_to current_user
    else
      flash[:alert] = "削除できませんでした"
      render :show
    end
  end

  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def join
    @project = Project.find(params[:id])
    if @project.users.pluck(:id).include?(current_user.id)
      flash[:notice] = "既に加入しています"
      redirect_to @project
    else
      @project.users << current_user
      redirect_to @project
    end
  end

  def leave
    @project = Project.find(params[:id])
    @project.users.delete(current_user)
    if @project.users.pluck(:id).exclude?(current_user.id)
      flash[:notice] = "脱退処理が完了しました"
      redirect_to current_user
    else
      flash[:alert] = "脱退できませんでした"
      redirect_to @project
    end
  end
  private
    def projects_params
      params.require(:project).permit(:name, :icon, :note, :topic1, :topic2, :topic3, :topic4, :topic5, :remove_icon)
    end
    def new_host(host_users)
      host_users.each do |host|
        Associate.where(user: host,project: @project).update(host: :true)
      end
    end
    def delete_host(non_host)
      non_host.each do |host|
        Associate.where(user: host,project: @project).update(host: :false)
      end
    end
    def set_host
      Associate.where(user: current_user, project: @project).update(host: true)
    end
  end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for([:admin, :survey, @free_choice_matter]) do |f| %>
  <div class="col">
    <% = f.label :subject %>
    <%= f.text_field :subject, class: 'form-control'  %>
  <div class="col">
    <div class="checkbox">
      <% label %>
      <%= f.check_box :other_selected  %>
      <%= f.label :other_selected  %>
  <%= f.fields_for :options do |option|  %>
    <%= render "option_fields", f: option  %>
  <div class="button_to ">
    <%= link_to_add_association "選択肢追加", f, :options, class: 'btn btn-success'  %>
  <div class="button_to">
    <%= f.submit class: 'btn btn-info'  %>
    -->
    <!-- showに "<%= render="form" %>" を実装してトピックをボタン追加にすることができる(多分)） -->

app/views/projects/_topic.html.erb
<div class="title">
  <div class="col">
    <%= f.label :topic1 %>
    <%= f.text_field :topic1 %>
  </div>
  <div class="col">
    <% if @project.topic2? %>
      <%= f.label :topic2 %>
      <%= f.text_field :topic2 %>
    <% end %>
  </div>
  <div class="col">
    <% if @project.topic3? %>
      <%= f.label :topic3 %>
      <%= f.text_field :topic3 %>
    <% end %>
  </div>
  <div class="col">
    <% if @project.topic4? %>
      <%= f.label :topic4 %>
      <%= f.text_field :topic4 %>
    <% end %>
  </div>
  <div class="col">
    <% if @project.topic5? %>
      <%= f.label :topic5 %>
      <%= f.text_field :topic5 %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class = "title">
  <h1>プロジェクト編集</h1>
  <div class = "button">
      <%= link_to :back, method: :get do %> <i class = "material-icons">arrow_back</i> Back<% end %>
    <%= link_to project_path(@project), data: { confirm: "本当によろしいですか?" }, method: :delete do %> <i class = "material-icons">delete</i>Delete <% end %>
  </div>
</div>
<hr>
<%= form_with model: @project do |form| %>
  <div class = "rowfield">
    <div class = "col">
      <div class="col">
        <%= form.label :icon %>
        <%= form.file_field :icon, type:"file", onchange:"previewImage()" %>
        <%= form.hidden_field :icon_cache %>
        <%= image_tag @project.icon.url,  id: 'preview' %>
        <label>
          <%= form.check_box :remove_icon %>
          画像を削除する
        </label>
      </div>
      <div class ="col">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class ="col">
        <%= form.label :note %>
        <%= form.text_area :note %>
      </div>
      <div class = "col">
        <h3>what you share?(limit 5 topic)</h3>
        <div class = "col">
          <%= form.label :topic1 %>
          <%= form.text_field :topic1 %>
          <%= form.label :topic2 %>
          <%= form.text_field :topic2 %>
          <%= form.label :topic3 %>
          <%= form.text_field :topic3 %>
          <%= form.label :topic4 %>
          <%= form.text_field :topic4 %>
          <%= form.label :topic5 %>
          <%= form.text_field :topic5 %>
        </div>
      </div>
    </div>
    <div class = "col">
      <div class = "rowfield">
        <div class = "col">
          <h3>追加する管理者</h3>
          <div class = "scroll">
            <div class = "col">
            <% @not_host_member.each do |user| %>
              <div class = "row">
                <%= form.check_box :host_users,  {multiple: true}, user.id, nil %>
                <%= user.name %>
              </div>
            <% end %>
            </div>
          </div>
        </div>
        <div class = "col">
          <h3>削除する管理者</h3>
          <div class = "scroll">
            <div class = "col">
              <% @host_member.each do |user| %>
                <div class = "row">
                  <%= form.check_box :non_host,  {multiple: true}, user.id, nil %>
                  <%= user.name %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class = "link">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>
<%= javascript_pack_tag "user/common.js" %>

app/views/projects/index.html.erb
<div class = "title">
  <h1>プロジェクト検索</h1>
  <div class = "button">
      <%= link_to :back, method: :get do %> <i class = "material-icons">arrow_back</i> Back<% end %>
  </div>
</div>
<hr>
<div class = "col">
  <div class = "title">
    <%= search_form_for @q do |f| %>
      <%= f.label :name_cont %>
      <%= f.search_field :name_cont %>
      <%= f.submit %>
    <% end %>
  </div>
  <div class = "rowitem">
    <% @projects.each do |project| %>
      <div>
        <h3><%= project.name %></h3>
        <%= image_tag project.icon.url %>
        <%= button_to "参加", join_project_path(project), method: :post %>
      </div>
    <% end %>
  </div>
  <%= paginate @projects %>
</div>

app/views/projects/new.html.erb
<div class = "title">
  <h1>プロジェクト作成</h1>
  <div class = "button">
      <%= link_to :back, method: :get do %> <i class = "material-icons">arrow_back</i> Back<% end %>
  </div>
</div>
<hr>
<%= form_with model: @project do |form| %>
  <div class = "col">
    <div class="col">
      <div class ="col">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="col">
        <%= form.label :note %>
        <%= form.text_area :note %>
      </div>
    </div>
    <div class="col">
      <p>what you share?(limit 5 topic)</p>
      <%= form.label :topic1 %>
      <%= form.text_field :topic1 %>
      <%= form.label :topic2 %>
      <%= form.text_field :topic2 %>
      <%= form.label :topic3 %>
      <%= form.text_field :topic3 %>
      <%= form.label :topic4 %>
      <%= form.text_field :topic4 %>
      <%= form.label :topic5 %>
      <%= form.text_field :topic5 %>
      <div class = "link">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class="title">
  <div class = "row">
    <%= image_tag @project.icon.url %>
    <h2>Project Name:<%= @project.name %></h2>
  </div>
  <div class = "button">
    <% if @host_member.include?(current_user)  %>
      <%= link_to edit_project_path, method: :get do %> <i class = "material-icons">edit</i>Edit <% end %>
    <% else %>
      <%= link_to leave_project_path(@project), method: :delete do %> <i class = "material-icons">person_off</i>Leave <% end %>
    <% end %>
    <%= link_to new_post_path(project_id: @project), method: :get do %> <i class = "material-icons">post_add</i>Post <% end %>
  </div>
</div>
<hr>
<div class="rowfield">
  <div class = "col">
    <div class = "scroll">
      <h3>管理者</h3>
      <% @host_member.each do |host| %>
        <p><%= host.name %></p>
      <% end %>
      <h3>メンバー</h3>
      <% @not_host_member.each do |member|%>
        <p><%= member.name %></p>
      <% end %>
    </div>
  </div>
  <div class = "wi col">
    <h3>投稿</h3>
    <div class = "row">
      <div><%= @project.topic1 %></div>
      <% if @project.topic2.present? %>
        <div><%= @project.topic2 %></div>
      <% end %>
      <% if @project.topic3.present? %>
        <div><%= @project.topic3 %></div>
      <% end %>
      <% if @project.topic4.present? %>
        <div><%= @project.topic4 %></div>
      <% end %>
      <% if @project.topic5.present? %>
        <div><%= @project.topic5 %></div>
      <% end %>
    </div>
    <div class = "col">
      <% @posts.each do |post| %>
        <div class = "colitem">
          <div><%= post.user.name %></div>
          <div class = "row">
            <div><%= post.post1 %></div>
            <% if @project.topic2.present? %>
                <div><%= post.post2 %></div>
            <% end %>
            <% if @project.topic3.present? %>
                <div><%= post.post3 %></div>
            <% end %>
            <% if @project.topic4.present? %>
                <div><%= post.post4 %></div>
            <% end %>
            <% if @project.topic5.present? %>
                <div><%= post.post5 %></div>
            <% end %>
          </div>
        </div>
      <% end %>
      <%= paginate @posts %>
    </div>
  </div>
</div>